name: StackScan Mercenary
on:
  repository_dispatch:
    types: [start_scan]

jobs:
  scan:
    runs-on: ubuntu-latest # Usamos la máquina estándar de GitHub con 7GB de RAM
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      # --- NIVEL 0: CACHÉ ACTIVADA ---
      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      # -------------------------------

      - name: Instalar dependencias
        run: npm install puppeteer-core

      - name: Ejecutar Escaneo Profundo
        env:
          SCAN_URL: ${{ github.event.client_payload.url }}
          CALLBACK_URL: ${{ github.event.client_payload.callback_url }}
          # Usamos el Chrome que ya viene preinstalado en el servidor de GitHub
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome
        run: node scanner.js
